In [1]:
from collections import Counter
from imblearn.datasets import fetch_datasets
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from imblearn.pipeline import make_pipeline as make_pipeline_imb
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import ComplementNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import KFold


In [2]:
data = pd.read_csv("DATA1.csv")
x=data[['koi_score','koi_period','koi_ror','koi_srho','koi_prad','koi_sma','koi_teq','koi_insol','koi_dor','koi_count','koi_steff','koi_slogg','koi_smet','koi_srad','koi_smass']]
y=data['O/P']
X_train, X_test, y_train, y_test = train_test_split(x,y,random_state=2)
len(X_train)
lr = LogisticRegression(max_iter = 100000)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           N       1.00      1.00      1.00      1986
           Y       0.88      0.58      0.70        12

    accuracy                           1.00      1998
   macro avg       0.94      0.79      0.85      1998
weighted avg       1.00      1.00      1.00      1998

[[1985    1]
 [   5    7]]


In [3]:
accuracy_model = []
smt = SMOTE()
kf = KFold(n_splits=10)
for train, test in kf.split(data):
    X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    X_train_S, y_train_S = smt.fit_sample(X_train, y_train)
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    accuracy_model.append(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
print(np.mean(accuracy_model))

0.9929078014184397
              precision    recall  f1-score   support

           N       0.99      1.00      1.00      2371
           Y       0.80      0.46      0.59        26

    accuracy                           0.99      2397
   macro avg       0.90      0.73      0.79      2397
weighted avg       0.99      0.99      0.99      2397

[[2368    3]
 [  14   12]]
0.9933249895702962
              precision    recall  f1-score   support

           N       0.99      1.00      1.00      2371
           Y       0.92      0.42      0.58        26

    accuracy                           0.99      2397
   macro avg       0.96      0.71      0.79      2397
weighted avg       0.99      0.99      0.99      2397

[[2370    1]
 [  15   11]]
0.9924906132665833
              precision    recall  f1-score   support

           N       0.99      1.00      1.00      2371
           Y       0.83      0.38      0.53        26

    accuracy                           0.99      2397
   macro avg     

In [4]:
smt = SMOTE()
X_train_S, y_train_S = smt.fit_sample(X_train, y_train,)
lr = LogisticRegression(max_iter = 100000)
lr.fit(X_train_S, y_train_S)
y_pred = lr.predict(X_test)
accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))


              precision    recall  f1-score   support

           N       1.00      0.97      0.98      2378
           Y       0.20      0.95      0.33        19

    accuracy                           0.97      2397
   macro avg       0.60      0.96      0.66      2397
weighted avg       0.99      0.97      0.98      2397

[[2307   71]
 [   1   18]]


In [5]:
accuracy_model = []
kf = KFold(n_splits=10)
for train, test in kf.split(data):
    X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    X_train_S, y_train_S = smt.fit_sample(X_train, y_train)
    lr.fit(X_train_S, y_train_S)
    y_pred = lr.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    accuracy_model.append(accuracy_score(y_test,y_pred))
print(np.mean(accuracy_model))

0.9787234042553191
              precision    recall  f1-score   support

           N       1.00      0.98      0.99      2374
           Y       0.29      0.87      0.44        23

    accuracy                           0.98      2397
   macro avg       0.65      0.92      0.71      2397
weighted avg       0.99      0.98      0.98      2397

0.9816437213183146
              precision    recall  f1-score   support

           N       1.00      0.98      0.99      2374
           Y       0.32      0.83      0.46        23

    accuracy                           0.98      2397
   macro avg       0.66      0.90      0.73      2397
weighted avg       0.99      0.98      0.99      2397

0.9712140175219024
              precision    recall  f1-score   support

           N       1.00      0.97      0.99      2366
           Y       0.31      0.97      0.47        31

    accuracy                           0.97      2397
   macro avg       0.65      0.97      0.73      2397
weighted avg     

In [6]:
X_train_S, y_train_S = smt.fit_sample(X_train, y_train,)
clf = svm.SVC(kernel = 'rbf')
clf.fit(X_train_S, y_train_S)
y_pred = clf.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

0.541927409261577
              precision    recall  f1-score   support

           N       1.00      0.54      0.70      2380
           Y       0.02      1.00      0.03        17

    accuracy                           0.54      2397
   macro avg       0.51      0.77      0.37      2397
weighted avg       0.99      0.54      0.70      2397

[[1282 1098]
 [   0   17]]


In [7]:
accuracy_model_2 = []
for train, test in kf.split(data):
    X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    X_train_S, y_train_S = smt.fit_sample(X_train, y_train)
    clf.fit(X_train_S, y_train_S)
    y_pred = clf.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    accuracy_model_2.append(accuracy_score(y_test,y_pred))
print(np.mean(accuracy_model_2))

0.6962870254484773
              precision    recall  f1-score   support

           N       1.00      0.69      0.82      2373
           Y       0.03      1.00      0.06        24

    accuracy                           0.70      2397
   macro avg       0.52      0.85      0.44      2397
weighted avg       0.99      0.70      0.81      2397

0.672924488944514
              precision    recall  f1-score   support

           N       1.00      0.67      0.80      2369
           Y       0.03      0.96      0.06        28

    accuracy                           0.67      2397
   macro avg       0.52      0.82      0.43      2397
weighted avg       0.99      0.67      0.79      2397

0.803087192323738
              precision    recall  f1-score   support

           N       1.00      0.80      0.89      2375
           Y       0.04      1.00      0.09        22

    accuracy                           0.80      2397
   macro avg       0.52      0.90      0.49      2397
weighted avg       

In [8]:
X_train_S, y_train_S = smt.fit_sample(X_train, y_train,)
RF = RandomForestClassifier(n_estimators = 100, min_samples_leaf = 2,min_samples_split = 10, max_depth = 100) 
RF.fit(X_train_S, y_train_S)
y_pred = RF.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

0.9920734251147267
              precision    recall  f1-score   support

           N       1.00      0.99      1.00      2380
           Y       0.46      0.76      0.58        17

    accuracy                           0.99      2397
   macro avg       0.73      0.88      0.79      2397
weighted avg       0.99      0.99      0.99      2397

[[2365   15]
 [   4   13]]


In [9]:
accuracy_model_3 = []
for train, test in kf.split(data):
    X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    X_train_S, y_train_S = smt.fit_sample(X_train, y_train)
    RF.fit(X_train_S, y_train_S)
    y_pred = RF.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    accuracy_model_3.append(accuracy_score(y_test,y_pred))
print(np.mean(accuracy_model_3))

0.9920734251147267
              precision    recall  f1-score   support

           N       1.00      0.99      1.00      2372
           Y       0.59      0.76      0.67        25

    accuracy                           0.99      2397
   macro avg       0.80      0.88      0.83      2397
weighted avg       0.99      0.99      0.99      2397

0.9920734251147267
              precision    recall  f1-score   support

           N       1.00      0.99      1.00      2376
           Y       0.53      0.81      0.64        21

    accuracy                           0.99      2397
   macro avg       0.76      0.90      0.82      2397
weighted avg       0.99      0.99      0.99      2397

0.9904046725073008
              precision    recall  f1-score   support

           N       1.00      0.99      1.00      2371
           Y       0.55      0.62      0.58        26

    accuracy                           0.99      2397
   macro avg       0.77      0.80      0.79      2397
weighted avg     

In [10]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range = (0,1))
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_test_minmax = min_max_scaler.fit_transform(X_test)
gnb = ComplementNB()
gnb.fit(X_train_minmax, y_train)
y_pred = gnb.predict(X_test_minmax)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

0.8639966624947851
              precision    recall  f1-score   support

           N       1.00      0.86      0.93      2378
           Y       0.05      0.89      0.09        19

    accuracy                           0.86      2397
   macro avg       0.52      0.88      0.51      2397
weighted avg       0.99      0.86      0.92      2397

[[2054  324]
 [   2   17]]


In [11]:
accuracy_model_4 = []
for train, test in kf.split(data):
    X_train_minmax, X_test_minmax, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    gnb.fit(X_train_minmax, y_train)
    y_pred = gnb.predict(X_test_minmax)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    accuracy_model_4.append(accuracy_score(y_test,y_pred))
print(np.mean(accuracy_model_4))

ValueError: Negative values in data passed to ComplementNB (input X)

In [12]:
X_train_S, y_train_S = smt.fit_sample(X_train, y_train,)
N = KNeighborsClassifier(n_neighbors=6)
N.fit(X_train_S, y_train_S)
y_pred = N.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))
print(f1_score(y_test,y_pred,average = 'micro'))

0.7701293283270755
              precision    recall  f1-score   support

           N       0.99      0.77      0.87      2379
           Y       0.01      0.22      0.01        18

    accuracy                           0.77      2397
   macro avg       0.50      0.50      0.44      2397
weighted avg       0.99      0.77      0.86      2397

[[1842  537]
 [  14    4]]
0.7701293283270755


In [13]:
accuracy_model_5 = []
for train, test in kf.split(data):
    X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    N = KNeighborsClassifier(n_neighbors=6)
    N.fit(X_train_S, y_train_S)
    y_pred = N.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    accuracy_model_5.append(accuracy_score(y_test,y_pred))
print(np.mean(accuracy_model_5))

0.8135168961201502
              precision    recall  f1-score   support

           N       0.99      0.82      0.90      2372
           Y       0.00      0.04      0.00        25

    accuracy                           0.81      2397
   macro avg       0.50      0.43      0.45      2397
weighted avg       0.98      0.81      0.89      2397

0.8114309553608677
              precision    recall  f1-score   support

           N       0.99      0.82      0.90      2373
           Y       0.01      0.17      0.02        24

    accuracy                           0.81      2397
   macro avg       0.50      0.49      0.46      2397
weighted avg       0.98      0.81      0.89      2397

0.8130997079682937
              precision    recall  f1-score   support

           N       0.99      0.82      0.90      2374
           Y       0.01      0.13      0.01        23

    accuracy                           0.81      2397
   macro avg       0.50      0.48      0.45      2397
weighted avg     